name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: 'bookstore'
          postgresql user: postgres
          postgresql password: password

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: ENV_SILENT=true npm test
        env:
          CI: true
          NODE_ENV: test
          PORT: 6379
          REDIS_SECRET: shshshshhs
          TEST_DATABASE_URL: postgres://postgres:password@127.0.0.1:5432/bookstore
          DATABASE_DIALECT: postgres
          DATABASE_DEBUG: false